### ISSUE TITLE
Problem 1: Testing : Test Example Component Updates

### ISSUE THREAD

**Issue by Sharu201101** [suhasss077/Project4#3]
As a developer, I want the assignee to ensure that the updates made to the Example component in Issue 1 function correctly and meet the desired criteria. This involves defining a comprehensive set of test cases to thoroughly test the component's behavior and user experience.

Test Cases:
Test Case 1: Display User's Name
As a developer of the Example component, I want the assignee to verify that the component correctly displays the name.
So that I can see the name displayed accurately.
Test Case 2: Initial Motto Load
As a developer of the Example component, I want the assignee to confirm that the displayed motto is initially loaded from the model data.
I want the assignee to ensure the motto is loaded correctly from the model data.
Test Case 3: Styling Verification
As a developer of the Example component, I want the assignee to validate that the displayed name and motto have the correct styling applied.
I want the assignee to ensure that the component provides a visually appealing user experience.

**Comment by ruchitha007** [comment]
Acceptance Criteria:

- Verified that the Example component correctly displays the user's name.
- Confirmed that the displayed motto is initially loaded from the model data.
- Validated that the displayed name and motto have the correct styling applied.
- Tested that the user can update the motto through the form input.

 Definition of Done:

- All test cases have been executed successfully, covering the identified scenarios related to the Example component updates.
- The Example component correctly displays the user's name.
- Once all these criteria have been met and validated, the "Test Example Component Updates" task is considered complete and ready for integration and deployment.
