### ISSUE TITLE
Problem2:Create a new component - states view

### ISSUE THREAD

**Issue by ruchitha007** [suhasss077/Project4#5]
Create States Component with Substring Filtering

As a developer, I want the assignee to see a component that displays states containing a given substring, so that I can easily find and filter states based on my search criteria.

Create a new React component called "States" that will display a list of states containing a given substring. Users should be able to enter a substring in an input field, and the component should update the list of states in real-time as the user types. If there are no matching states, display a message indicating this.

**Comment by Sharu201101** [comment]
Acceptance Criteria:

- Implement the "States" React component.
- Display an input field for entering a substring.
- Update the list of states in real-time as the user types in the input field.
- Display the filtered states in alphabetical order.
- If there are no matching states, display a message indicating this.
- Implement appropriate styling for the component.

import React from 'react';
import './States.css';

class States extends React.Component {
  constructor(props) {
    super(props);
this.state = {
  val: '',
};
}

function = () => {
  var li=[];
  const { val } = this.state;
  li=window.models.states().filter((state) =>  state.toLowerCase().includes(val)  );
  return li;
  };

handlingChange = (e) => {
this.setState({ val: e.target.value.toLowerCase() });
};

render() {
const filteredStates = this.function();

return (
  <div >
    <h1 style={{
  textAlign: 'center',      // Center the text horizontally
  backgroundColor: 'lightblue', // Add background color
  color: 'darkblue',         // Set text color
  padding: '10px'           // Add some padding for spacing
}}>
  States View
    </h1>
<p>You Can Enter Text Here</p>
    <input
  type="text"
  placeholder="Enter Text"
  value={this.state.val}
  onChange={this.handlingChange}
  style={{
    padding: '10px',                 // Add padding
    fontSize: '16px',                // Set font size
    borderRadius: '5px',             // Add rounded corners
    border: '2px solid #3498db',     // Add a border
    boxShadow: '0px 0px 10px rgba(0, 0, 0, 0.1)', // Add a subtle shadow
    outline: 'none',                 // Remove the default outline
    transition: 'border 0.3s',       // Add a smooth transition on hover
  }}
  // eslint-disable-next-line no-return-assign
  onFocus={(e) => e.target.style.border = '2px solid #e74c3c'} // Change border color on focus
  // eslint-disable-next-line no-return-assign
  onBlur={(e) => e.target.style.border = '2px solid #3498db'} // Restore original border color on blur
/>

    <p>You can see the output after entering</p>

    {filteredStates.length !== 0 ? (
  <ul style={{ listStyle: 'none', padding: 0 }}>
    {filteredStates.map((state, ind) => (
      <li
        key={ind}
        style={{
          margin: '5px 0',
          backgroundColor: '#E8ECFD',
          color: 'navy',               
          fontSize: '25px',            
        }}
      >
        {state}
      </li>
    ))}
  </ul>
) : (
  <p style={{ color: 'lightcoral', fontStyle: 'italic', fontSize: '18px' }}>
    No states with mentioned words
  </p>
)}


  </div>
);
}
}

export default States;


Definition of Done : 

- The "States" React component has been successfully implemented as specified in the issue.
- The component includes an input field that allows users to enter a substring.
