### ISSUE TITLE
Problem2:Test States Component for Substring Filtering

### ISSUE THREAD

**Issue by ruchitha007** [suhasss077/Project4#6]
As a developer, I want the assignee to test the "States" component to ensure that it correctly filters states based on a given substring, so that we can verify its functionality and reliability.

 Define a set of test cases to verify that the "States" component correctly filters states based on the entered substring. These tests should cover various scenarios and edge cases to ensure the component's robustness.

Test Case 1: Verify Filtering with a Matching Substring
Test Scenario: The user enters a substring that matches multiple states in the list.
Test Steps:
Enter the substring "al" into the input field.
Observe the list of displayed states.
Expected Result: The component should display a list of states containing the substring "al," such as "Alabama," "Alaska," and "California."

Test Case 2: Verify Filtering with No Matching Substring
Test Scenario: The user enters a substring that does not match any states in the list.
Test Steps:
Enter the substring "xyz" into the input field.
Observe the displayed message.
Expected Result: The component should display a message indicating that no matching states were found.

**Comment by Sharu201101** [comment]
Comments : 

- Verified that the component filters states correctly based on the entered substring.
- Tested the component with different substrings and check if it displays the expected states.
- Ensured that the list of states is updated in real-time as the user types.
- Confirmed that the component ignores the case when filtering.

**Comment by Sharu201101** [comment]
Testing Done
